<?php defined('BASEPATH') or exit('No direct script access allowed');

/* ----------------------------------------------------------------------------
 * Easy!Appointments - Online Appointment Scheduler
 *
 * @package     EasyAppointments
 * @license     https://opensource.org/licenses/GPL-3.0 - GPLv3
 * ---------------------------------------------------------------------------- */

/**
 * Confirmation PDF controller.
 *
 * Serves the appointment confirmation PDF generated by `Appointment_confirmation_pdf`.
 *
 * Access model:
 *  - `download/{hash}`  → Public endpoint identified by the non-sequential appointment hash.
 *                         Mirrors the existing reschedule link model so the customer can use
 *                         the URL embedded in their confirmation email. 404 if the hash does
 *                         not match any appointment.
 *  - `admin/{id}`       → Requires an authenticated session with `view` permission on
 *                         appointments. Accepts the numeric id because the admin already
 *                         identifies appointments by id from the backend UI.
 *
 * @package Controllers
 */
class Confirmation_pdf extends EA_Controller
{
    public function __construct()
    {
        parent::__construct();

        $this->load->model('appointments_model');
        $this->load->library('appointment_confirmation_pdf');
    }

    /**
     * Public endpoint: serve the PDF by appointment hash.
     *
     * Always identifies by hash, never by numeric id, to avoid leaking appointment data
     * through id enumeration.
     *
     * @param string $hash The `ea_appointments.hash` value.
     */
    public function download(string $hash = ''): void
    {
        $hash = trim($hash);

        if ($hash === '') {
            show_404();
            return;
        }

        $matches = $this->appointments_model->get(['hash' => $hash]);

        if (empty($matches)) {
            show_404();
            return;
        }

        $this->stream_pdf((int) $matches[0]['id'], $matches[0]['folio'] ?? null);
    }

    /**
     * Admin endpoint: serve the PDF by appointment id, gated by session + permission check.
     *
     * @param int $appointment_id The `ea_appointments.id` value.
     */
    public function admin(int $appointment_id = 0): void
    {
        if (!session('user_id')) {
            redirect('login');
            return;
        }

        if (cannot('view', PRIV_APPOINTMENTS)) {
            abort(403, 'Forbidden');
            return;
        }

        if ($appointment_id <= 0) {
            show_404();
            return;
        }

        try {
            $appointment = $this->appointments_model->find($appointment_id);
        } catch (Throwable $e) {
            show_404();
            return;
        }

        $this->stream_pdf((int) $appointment['id'], $appointment['folio'] ?? null);
    }

    /**
     * Render the PDF and stream it to the browser.
     *
     * @param int         $appointment_id
     * @param string|null $folio The appointment folio (used to compose the download filename).
     */
    private function stream_pdf(int $appointment_id, ?string $folio): void
    {
        try {
            $pdf_bytes = $this->appointment_confirmation_pdf->generate($appointment_id);
        } catch (Throwable $e) {
            log_message('error', 'Confirmation PDF generation failed for appointment ' . $appointment_id . ': ' . $e->getMessage());
            show_error('No se pudo generar el PDF de confirmación.', 500);
            return;
        }

        $filename = !empty($folio)
            ? 'Confirmacion-' . $folio . '.pdf'
            : 'Confirmacion-cita-' . $appointment_id . '.pdf';

        $disposition = request('download') ? 'attachment' : 'inline';

        $this->output
            ->set_content_type('application/pdf')
            ->set_header('Content-Disposition: ' . $disposition . '; filename="' . $filename . '"')
            ->set_header('Cache-Control: private, max-age=0, must-revalidate')
            ->set_output($pdf_bytes);
    }
}
